FROM alpine:latest
RUN apk --no-cache add jq 

ENV CHANNEL_ID="86442135xxxxxxxxxx"
ENV BOT_TOKEN="ODY2NjUyNjEzNzxxxxxxxxxx.xxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx"
ENV SECRETURL="https://xxxxxxxxxx:xxxx/xxxxxxxxxxxxxxxx/access-keys"
ENV ROLE_CALL="86404724xxxxxxxxxx"
ENV ROLE_COM="86404982xxxxxxxxxx"
ENV ROLE_DATA="86404773xxxxxxxxxx"
ENV ROLE_FB="86404996xxxxxxxxxx"
ENV ROLE_WEB="86405010xxxxxxxxxx"

RUN mkdir /app
WORKDIR /app
RUN wget -q -nv -O- https://api.github.com/repos/peterzam/asterbot/releases/latest 2>/dev/null |  jq -r '.assets[2] | select(.browser_download_url) | .browser_download_url' | xargs wget -O -  | tar -xz

CMD [ "/app/OutlineBot" ]